### ISSUE TITLE
Somn: Warning Messages for Stereochemistry and Heavy Atoms

### ISSUE THREAD

**Issue by David-Bianchi** [moleculemaker/somn-frontend#25]
Warning messages upon Somn SMILES input validation for molecules containing stereochemistry (dashes etc.) or heavy atoms (more than 150 atoms etc.)

1. Stereochemistry

See the following Slack link for David's initial pybel code for this: https://moleculemakerlabinst.slack.com/archives/C064A6PR01M/p1724949118827219

**Link for Figma designs**: https://www.figma.com/design/XMOJNiIiIK7Q8zdRIWBFE5?node-id=1956-26304#930837523

![Image](https://github.com/user-attachments/assets/e1ffedb5-1db1-45f0-831e-25cfb90b83f7)

2. Heavy atoms (greater than 150 atoms)

See the following Slack link for David's initial pybel code for this: https://moleculemakerlabinst.slack.com/archives/C064A6PR01M/p1727891243631019

**Link for Figma designs**: https://www.figma.com/design/XMOJNiIiIK7Q8zdRIWBFE5?node-id=2000-26785#959605189

![Image](https://github.com/user-attachments/assets/b972dd6e-ced5-42ec-a8da-8877edc0d6a2)

**Comment by ckouder** [comment]
Hi David, thank you for creating this issue! Will take a look next week or Friday if have time

**Comment by David-Bianchi** [comment]
Sounds good, thanks Bingji! Let me know here or in Slack if you have any questions on it.

**Comment by ckouder** [comment]
Hi David, please let me know if this [issue](https://github.com/openbabel/openbabel/issues/2416https://www.figma.com/design/XMOJNiIiIK7Q8zdRIWBFE5/Somn#930837523) still persists with openbabel parsing cdxml? This might be covered before but i'd like to double check to make sure if I use the right tool

**Comment by David-Bianchi** [comment]
@ckouder, this is a good point! The openbabel code should work for this, we just have to double check that it doesn't leave any "open valences" (which would show up as two extraneous dots over an atom in the image), and that the Hs get properly added with .addHs() and the pull request mentioned in the issue that you shared above.

**Comment by ckouder** [comment]
this is blocked on https://github.com/moleculemaker/mmli-backend/issues/63 - other parts are under review
